name: CI
# 在push的时候触发这个workflow
on: [push]
# workflow的job内容
jobs:
  build:
    # 跑job的系统
    runs-on: ubuntu-latest
    # 定义需要跑的脚本
    steps:
    # 使用checkout action
    - uses: actions/checkout@v2
    # Hello World
    - name: Run a one-line script
      run: echo Hello, world!
    # 打印多行
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
